//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Server.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SERVERTYPE                  129
#define IDR_CLIENTERR                   130
#define IDR_CLIENTOFF                   131
#define IDR_CLIENTON                    132
#define ID_EMPTY1_EMPTYA                32771
#define ID_EMPTY1_EMPTYB                32772
#define ID_EMPTY2_EMPTYA                32773
#define ID_EMPTY2_EMPTYB                32774
#define ID_MAINTIMER                    61204
#define ID_RECORDS                      61205
#define ID_COMM_INIT_STRING             61207
#define ID_CONNECT_STATEMENT            61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
